<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CliWrap, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
    <Reference Include="TabStrip, Version=2.0.2523.29272, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>.\TabStrip.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="TabStrip.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\cc65Wrapper\cc65Wrapper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FCTB" Version="2.16.24" />
  </ItemGroup>
</Project>